name: 检查新版本

on:
  schedule:
    # 每天 UTC 00:00（北京时间 08:00）执行一次
    - cron: "0 0 * * *"
  # 支持手动触发
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    # 声明这个 Job 要向外暴露的 outputs
    outputs:
      should_approve: ${{ steps.check_version.outputs.should_approve }}
      latest_tag: ${{ steps.check_version.outputs.latest_tag }}

    steps:
      - name: Checkout current repo code
        uses: actions/checkout@v6

      # 1. 查询目标仓库最新Release
      - name: Get latest release of target repo
        id: get_remote_release
        run: |
          # 获取apache/rocketmq最新release
          RAW_TAG=$(gh api repos/apache/rocketmq/releases/latest --jq '.tag_name')
          LATEST_TAG=$(echo "$RAW_TAG" | sed -E 's/^[^0-9]+//')
          echo "REMOTE_RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "REMOTE_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest remote: tag: $RAW_TAG, version: $LATEST_TAG"

      # 2. 查询本仓库最新Release
      - name: Get latest release of self repo
        id: read_last
        run: |
          # 获取apache/rocketmq最新release
          LATEST_TAG=$(gh api repos/ouchonghui/rocketmq-docker/releases/latest --jq '.tag_name')
          echo "SELF_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest self tag: $LATEST_TAG"

      # 3. 判断版本是否一致，相同则直接终止流程
      - name: Check version
        id: check_version
        run: |
          if [ "$REMOTE_LATEST_TAG" != "$SELF_LATEST_TAG" ]; then
            echo "发现新版本: $REMOTE_LATEST_TAG"
            echo "should_approve=true" >> "$GITHUB_OUTPUT"
            echo "latest_tag=$REMOTE_LATEST_TAG" >> "$GITHUB_OUTPUT"
          else
            echo "版本未更新，当前最新版本 rocketmq-$REMOTE_LATEST_TAG 与本地记录一致，无需发布，退出流程"
            echo "should_approve=false" >> "$GITHUB_OUTPUT"
          fi

  create-release:
    runs-on: ubuntu-latest
    environment: 发布版本
    needs: check-version
    if: needs.check-version.outputs.should_approve == 'true'
    steps:
      - name: Checkout current repo code
        uses: actions/checkout@v6

      # 自动创建Release发布
      - name: Create new release
        run: |
          gh release create ${{ needs.check-version.outputs.latest_tag }} \
            --title "Auto Sync Release rocketmq-${{ needs.check-version.outputs.latest_tag }}" \
            --notes "Auto generated by GitHub Action, sync with 'apache/rocketmq' latest release"
